In [1]:
print("hello world")

hello world


In [2]:
print('hello world')

hello world


In [3]:
age=23
age=24
print(age)

24


In [4]:
age=20
price=19.95
first_name='Mosh'
is_online=False
print(is_online)

False


In [5]:
#receiving input
name= input("What is your name")
print("Hello" + " " + name)

What is your nameJhansi
Hello Jhansi


In [6]:
birth_year=input("enter your birth year: ")
age=2023-int(birth_year)
print(age)

enter your birth year2000
23


In [7]:
int()
float()
bool()
str()


''

In [8]:
num1=float(input("enter num1: "))
num2=float(input("enter num2: "))
sum=num1+num2
print(sum)
print("sum "+ str(sum))

enter num1: 1
enter num2: 1.5
2.5
sum 2.5


In [9]:
course='python for beginners'
print(course.upper())
print(course)
print(course.lower())
print(course.find('y'))
print(course.find('Y'))# Y is not present
print(course.find('for'))
print(course.replace('for','4'))
print('python' in course)

PYTHON FOR BEGINNERS
python for beginners
python for beginners
1
-1
7
python 4 beginners
True


In [10]:
print(10+3)
print(10-3)
print(10*3)
print(10/3)# gets floating number
print(10//3)# gets integer i.e, whole number
print(10%3)
print(10**3)

13
7
30
3.3333333333333335
3
1
1000


In [11]:
x=10
x=x+3
x+=3
x-=3
x*=3


In [12]:
#precedence
x=10+3*2
print(x)
x=(10+3)*2
print(x)

16
26


In [13]:
#comparison operator
x=3>2
print(x)
x=3==2
print(x)
# >, >=, <, <=, ==, !=

True
False


In [15]:
price = 25
print(price > 10 or price < 30)
price=5
print(not price>10)
# and (true if both the expressions are true)
# or(true if one of the expressions is true)
#not(inverse the expression)

True
True


In [22]:
temperature=15
if temperature > 30:
    print("It's a hot day ")
    print("Drink plenty of water")
elif temperature>20: #(20,30]
    print("It's a nice day")
elif temperature>10: #(10,20]
    print("It's a bit cold")
print("Done")    


It's a bit cold
Done


In [3]:
i=1
while i<=5:
    print(i)
    i=i+1;


1
2
3
4
5


In [7]:
i=0
while i<=1_00:
    print(i * '*')
    i=i+10;


**********
********************
******************************
****************************************
**************************************************
************************************************************
**********************************************************************
********************************************************************************
******************************************************************************************
****************************************************************************************************


In [13]:
#lists
names=["Jhansi", "Jeet", "John", "Jack", "jockey"]
print(names[0])
print(names[-1])
print(names[-2])
names[0]="Sai Jhansi"
print(names)
print(names[0:3])

Jhansi
jockey
Jack
['Sai Jhansi', 'Jeet', 'John', 'Jack', 'jockey']
['Sai Jhansi', 'Jeet', 'John']


In [17]:
#list methods
nums=[1,2,3,4,5]
nums.append(6) # inserts at the last
print(nums)

nums.insert(0,-1)
print(nums)

nums.remove(3)
print(nums)

print(1 in nums)

print( len(nums))

for item in nums:
    print(item)

print("sai")
print("sai\n")
print("s\taij\than\tsi")
print()
i=0
while i< len(nums):
    print(nums[i])
    i=i+1;


nums.clear()
print(nums)

print(1 in nums)

[1, 2, 3, 4, 5, 6]
[-1, 1, 2, 3, 4, 5, 6]
[-1, 1, 2, 4, 5, 6]
True
6
-1
1
2
4
5
6
sai
sai

s	aij	han	si

-1
1
2
4
5
6
[]
False


In [15]:
#range
numbers=range(5)
print(numbers)

numbers=range(5)
for numbers in numbers:
    print(numbers)
    
numbers=range(5,10)
for numbers in numbers:
    print(numbers)

numbers=range(5,10,2)
for numbers in numbers:
    print(numbers)
    
for numbers in range(5):
    print(numbers)


range(0, 5)
0
1
2
3
4
5
6
7
8
9
5
7
9
0
1
2
3
4


In [37]:
# tuples are immutable
numbers=(1,2,3,3)
numbers.count(3)

2

In [71]:
#NumPy
import numpy as np # import the numpy library
# create a Numpy array(1D Array)
arr1= np.array([10,13,30])# Creating a 1D array (like a simple list)
arr=np.append(arr1,4)
print("1D Array after appending", arr)
print("1D Array", arr1)

arr2=np.array([[10,6,20],[1,26,3]])#2D array(like a table or matrix)
print("2D array\n", arr2)
# Step 3: Array operations
print("Shape of array2:", arr2.shape)#2x3 matrix, 2 -> rows, 3 -> col
print("Size of array2:", arr2.size)# gives no of elements in arr2
print(arr1+10)#1D matrix addidtion
print("arr1 - 10:", arr1 - 10)
print("arr1 * 10:", arr1 * 10)
print("arr1 / 10:", arr1 / 10)# gives quotient after dividing with 10
print("arr1 % 10:", arr1 % 10)# % -> gives remainder    " "
print("arr1 // 10:", arr1 // 10)# // -> floor divison, gives rounded off quotient 
print("arr1 **10:", arr1 ** 10)#  ** is the exponentiation operator, gives each element of arr1 to the power of 10
print()
print()
print(arr2+2)
print(arr2-2)#
print(arr2*2)#2D matrix myltiplication

zero_arr=np.zeros((2,3))#create an array of zeroes in 2X3 matrix
print("zeros array:\n", zeros_arr)

ones_arr=np.ones((3,2))#create an array of ones in 3X2 matrix
print("ones array:\n", ones_arr)

range_arr=np.arange(1,11)
print("Range array:", range_arr)# gives array with range:from 1 to 10

print(np.mean(arr1))
print(np.sum(arr1))

#Reshaping arrays

matrix = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = matrix.reshape(3, 2)

print("Original:\n", matrix)
print("Reshaped:\n", reshaped)

reshaped=arr1.reshape(3,1)
print("Reshaped arr1 to 3x1:\n", reshaped)


1D Array after appending [10 13 30  4]
1D Array [10 13 30]
2D array
 [[10  6 20]
 [ 1 26  3]]
Shape of array2: (2, 3)
Size of array2: 6
[20 23 40]
arr1 - 10: [ 0  3 20]
arr1 * 10: [100 130 300]
arr1 / 10: [1.  1.3 3. ]
arr1 % 10: [0 3 0]
arr1 // 10: [1 1 3]
arr1 **10: [1410065408  419538377  716276736]


[[12  8 22]
 [ 3 28  5]]
[[ 8  4 18]
 [-1 24  1]]
[[20 12 40]
 [ 2 52  6]]
zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range array: [ 1  2  3  4  5  6  7  8  9 10]
17.666666666666668
53
Original:
 [[1 2 3]
 [4 5 6]]
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped arr1 to 3x1:
 [[10]
 [13]
 [30]]


In [1]:
#pandas
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}

df = pd.DataFrame(data)
print(df)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [ ]:

#Pandas is a powerful Python library used for data analysis and manipulation.

#Lets you work with tables of data (like Excel sheets or SQL tables) easily.

#Helps with reading/writing CSV, Excel, JSON, and more.

#Makes it simple to clean, filter, group, sort, reshape, and analyze data.